from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator

CONTRACT_VERSION = "2.0"
SCHEMA_DRAFT = "https://json-schema.org/draft/2020-12/schema"
KEEP_SOURCE_SCHEMA = {"type": "string", "enum": ["cli", "config"]}


def object_schema(properties: dict[str, Any], required: list[str] | None = None) -> dict[str, Any]:
    return {
        "$schema": SCHEMA_DRAFT,
        "type": "object",
        "additionalProperties": True,
        "required": required or [],
        "properties": properties,
    }


def array_schema(properties: dict[str, Any], required: list[str] | None = None) -> dict[str, Any]:
    return {
        "$schema": SCHEMA_DRAFT,
        "type": "array",
        "items": object_schema(properties, required=required),
    }


def search_standard_properties(include_rank: bool) -> dict[str, Any]:
    properties: dict[str, Any] = {
        "event_id": {"type": "integer"},
        "session_id": {"type": "string"},
        "timestamp": {"type": ["string", "null"]},
        "top_type": {"type": "string"},
        "sub_type": {"type": ["string", "null"]},
        "role": {"type": ["string", "null"]},
        "tool_name": {"type": ["string", "null"]},
        "file_path": {"type": ["string", "null"]},
        "snippet": {"type": ["string", "null"]},
    }
    if include_rank:
        properties["rank"] = {"type": ["number", "null"]}
    return properties


def contract_schemas() -> dict[str, dict[str, Any]]:
    return {
        "search_minimal": array_schema(
            {
                "event_id": {"type": "integer"},
                "session_id": {"type": "string"},
            },
            required=["event_id", "session_id"],
        ),
        "search_standard": array_schema(search_standard_properties(include_rank=False), required=["event_id", "session_id"]),
        "search_full": array_schema(search_standard_properties(include_rank=True), required=["event_id", "session_id"]),
        "capabilities": object_schema(
            {
                "name": {"type": "string"},
                "contract_version": {"type": "string"},
                "schema_version": {"type": "integer"},
                "stability_policy": {"type": "string"},
                "commands": {"type": "array", "items": {"type": "string"}},
                "json_outputs": {"type": "array", "items": {"type": "string"}},
                "export_formats": {"type": "array", "items": {"type": "string"}},
                "export_profiles": {"type": "array", "items": {"type": "string"}},
                "privacy_modes": {"type": "array", "items": {"type": "string"}},
                "retrieval_modes": {"type": "array", "items": {"type": "string"}},
                "search_fields": {"type": "array", "items": {"type": "string"}},
                "interface_policy": {"type": "object"},
                "feature_flags": {"type": "object"},
            },
            required=[
                "name",
                "contract_version",
                "schema_version",
                "stability_policy",
                "commands",
                "json_outputs",
                "export_formats",
                "export_profiles",
                "privacy_modes",
                "retrieval_modes",
                "search_fields",
                "interface_policy",
                "feature_flags",
            ],
        ),
        "stats": object_schema(
            {
                "sessions": {"type": "integer"},
                "events": {"type": "integer"},
                "turns": {"type": "integer"},
                "warnings": {"type": "integer"},
                "projects": {"type": "integer"},
                "tool_calls": {"type": "integer"},
                "files": {"type": "integer"},
                "first_seen_at": {"type": ["string", "null"]},
                "updated_at": {"type": ["string", "null"]},
                "search_index": {"type": "object"},
            },
            required=["sessions", "events", "turns", "warnings"],
        ),
        "storage_audit": object_schema(
            {
                "ok": {"type": "boolean"},
                "db_path": {"type": "string"},
                "db_bytes": {"type": "integer"},
                "schema_version": {"type": "integer"},
                "cold_root": {"type": "string"},
                "event_totals": {"type": "object"},
                "by_type": {"type": "array"},
                "by_storage_class": {"type": "array"},
                "cold": {"type": "object"},
                "sqlite": {"type": "object"},
                "policy": {"type": "object"},
            },
            required=["ok", "db_path", "db_bytes", "schema_version", "cold_root", "event_totals", "cold"],
        ),
        "storage_rebuild": object_schema(
            {
                "ok": {"type": "boolean"},
                "applied": {"type": "boolean"},
                "source_db": {"type": "string"},
                "target_db": {"type": "string"},
                "cold_root": {"type": "string"},
                "validations": {"type": "object"},
            },
            required=["ok", "applied", "source_db", "target_db", "cold_root"],
        ),
        "storage_verify": object_schema(
            {
                "ok": {"type": "boolean"},
                "cold_root": {"type": "string"},
                "blobs": {"type": "integer"},
                "missing": {"type": "integer"},
                "invalid": {"type": "integer"},
                "deep": {"type": "boolean"},
                "errors": {"type": "array"},
            },
            required=["ok", "cold_root", "blobs"],
        ),
        "storage_prune": object_schema(
            {
                "ok": {"type": "boolean"},
                "applied": {"type": "boolean"},
                "db_path": {"type": "string"},
                "cold_root": {"type": "string"},
                "referenced_blobs": {"type": "integer"},
                "unreferenced_metadata": {"type": "integer"},
                "orphan_files": {"type": "integer"},
                "reclaimable_bytes": {"type": "integer"},
            },
            required=["ok", "applied", "db_path", "cold_root", "referenced_blobs", "reclaimable_bytes"],
        ),
        "storage_event": object_schema(
            {
                "event_id": {"type": "integer"},
                "storage_class": {"type": ["string", "null"]},
                "payload_ref": {"type": ["string", "null"]},
                "payload": {},
                "text_content": {"type": ["string", "null"]},
            },
            required=["event_id", "payload", "text_content"],
        ),
        "storage_backup": object_schema(
            {
                "ok": {"type": "boolean"},
                "profile": {"type": "string"},
                "database": {"type": "object"},
                "cold": {"type": "object"},
                "forensic_files": {"type": "integer"},
                "manifest": {"type": "string"},
            },
            required=["ok", "profile", "database"],
        ),
        "storage_backup_verify": object_schema(
            {
                "ok": {"type": "boolean"},
                "manifest": {"type": "string"},
                "profile": {"type": ["string", "null"]},
                "database": {"type": "object"},
                "database_sha256_ok": {"type": "boolean"},
                "cold": {"type": ["object", "null"]},
                "forensic_errors": {"type": "array"},
            },
            required=["ok", "manifest"],
        ),
        "storage_auto": object_schema(
            {
                "contract_version": {"type": "string"},
                "ok": {"type": "boolean"},
                "applied": {"type": "boolean"},
                "action": {"type": "string"},
                "profile": {"type": ["string", "null"]},
                "reason": {"type": "string"},
                "db_path": {"type": "string"},
                "out_root": {"type": "string"},
                "policy": {"type": "object"},
                "source_sync": {"type": "object"},
                "archive_state": {"type": "object"},
                "latest": {"type": "object"},
                "disk": {"type": "object"},
                "backup": {"type": ["object", "null"]},
                "verification": {"type": ["object", "null"]},
                "retention": {"type": ["object", "null"]},
            },
            required=[
                "contract_version", "ok", "applied", "action", "profile", "reason",
                "db_path", "out_root", "policy", "source_sync", "archive_state", "latest", "disk",
            ],
        ),
        "storage_sync": object_schema(
            {
                "contract_version": {"type": "string"},
                "ok": {"type": "boolean"},
                "fresh": {"type": "boolean"},
                "applied": {"type": "boolean"},
                "db_path": {"type": "string"},
                "codex_home": {"type": "string"},
                "source_files": {"type": "integer"},
                "pending_files": {"type": "integer"},
                "pending_bytes": {"type": "integer"},
                "pending_reasons": {"type": "object"},
                "import_stats": {"type": ["object", "null"]},
            },
            required=[
                "contract_version", "ok", "fresh", "applied", "db_path", "codex_home",
                "source_files", "pending_files", "pending_bytes", "pending_reasons", "import_stats",
            ],
        ),
        "doctor": object_schema(
            {
                "ok": {"type": "boolean"},
                "checks": {"type": "array"},
                "stats": {"type": "object"},
                "parse_health": {"type": "object"},
                "schema_version": {"type": "integer"},
                "schema_objects": {"type": "object"},
                "maintenance_suggestions": {"type": "array"},
                "python": {"type": "string"},
                "platform": {"type": "string"},
                "db_path": {"type": "string"},
                "codex_home": {"type": "string"},
                "session_dirs": {"type": "array", "items": {"type": "string"}},
                "missing_session_dirs": {"type": "array", "items": {"type": "string"}},
                "jsonl_files": {"type": "integer"},
                "codex_state": {"type": "object"},
            },
            required=[
                "ok",
                "checks",
                "stats",
                "parse_health",
                "schema_version",
                "schema_objects",
                "maintenance_suggestions",
                "python",
                "platform",
                "db_path",
                "codex_home",
                "session_dirs",
                "missing_session_dirs",
                "jsonl_files",
                "codex_state",
            ],
        ),
        "privacy_scan": object_schema(
            {
                "session_id": {"type": "string"},
                "rules_version": {"type": "string"},
                "findings": {"type": "array"},
                "summary": {"type": "object"},
            },
            required=["session_id", "rules_version", "findings", "summary"],
        ),
        "warnings_summary": array_schema(
            {
                "code": {"type": "string"},
                "count": {"type": "integer"},
            },
            required=["code", "count"],
        ),
        "corpus_audit": object_schema(
            {
                "privacy_note": {"type": "string"},
                "include_paths": {"type": "boolean"},
                "files": {"type": "integer"},
                "parseable_files": {"type": "integer"},
                "parseable_ratio": {"type": "number"},
                "events": {"type": "integer"},
                "warnings": {"type": "integer"},
                "warning_codes": {"type": "object"},
                "classifications": {"type": "object"},
                "samples": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": True,
                        "required": ["sample_id", "events", "warnings", "classifications", "warning_codes"],
                        "properties": {
                            "sample_id": {"type": "string"},
                            "events": {"type": "integer"},
                            "warnings": {"type": "integer"},
                            "classifications": {"type": "object"},
                            "warning_codes": {"type": "object"},
                            "path": {"type": "string"},
                            "session_id": {"type": "string"},
                        },
                    },
                },
            },
            required=["privacy_note", "include_paths", "files", "parseable_files", "samples"],
        ),
        "corpus_audit_report": object_schema(
            {
                "report_version": {"type": "string"},
                "generated_at": {"type": "string"},
                "source": {"type": ["string", "null"]},
                "limit": {"type": ["integer", "null"]},
                "privacy_note": {"type": "string"},
                "include_paths": {"type": "boolean"},
                "files": {"type": "integer"},
                "parseable_files": {"type": "integer"},
                "parseable_ratio": {"type": "number"},
                "events": {"type": "integer"},
                "warnings": {"type": "integer"},
                "warning_codes": {"type": "object"},
                "classifications": {"type": "object"},
                "samples": {"type": "array"},
                "report_path": {"type": "string"},
            },
            required=["report_version", "generated_at", "privacy_note", "include_paths", "files", "samples"],
        ),
        "corpus_audit_diff": object_schema(
            {
                "report_version": {"type": "string"},
                "before_generated_at": {"type": ["string", "null"]},
                "after_generated_at": {"type": ["string", "null"]},
                "files_delta": {"type": "integer"},
                "events_delta": {"type": "integer"},
                "warnings_delta": {"type": "integer"},
                "parseable_ratio_delta": {"type": "number"},
                "warning_code_deltas": {"type": "object"},
                "classification_deltas": {"type": "object"},
                "regressions": {"type": "object"},
            },
            required=["report_version", "files_delta", "events_delta", "warnings_delta", "regressions"],
        ),
        "audit_history_list": object_schema(
            {
                "dir": {"type": "string"},
                "reports": {"type": "array"},
                "warnings": {"type": "array"},
            },
            required=["dir", "reports", "warnings"],
        ),
        "audit_history_latest": object_schema(
            {
                "dir": {"type": "string"},
                "reports": {"type": "array"},
                "warnings": {"type": "array"},
                "latest": {"type": ["object", "null"]},
            },
            required=["dir", "reports", "warnings", "latest"],
        ),
        "audit_history_prune": object_schema(
            {
                "dir": {"type": "string"},
                "reports": {"type": "array"},
                "warnings": {"type": "array"},
                "ok": {"type": "boolean"},
                "apply": {"type": "boolean"},
                "keep": {"type": "integer"},
                "keep_source": KEEP_SOURCE_SCHEMA,
                "kept": {"type": "array"},
                "deletable": {"type": "array"},
                "deleted": {"type": "array", "items": {"type": "string"}},
            },
            required=["dir", "reports", "warnings", "ok", "apply", "keep", "keep_source", "kept", "deletable", "deleted"],
        ),
        "ingestion_enqueue": object_schema(
            {
                "ok": {"type": "boolean"},
                "enqueued": {"type": "boolean"},
                "status": {"type": "string"},
                "message": {"type": "string"},
                "request": {"type": "object"},
            },
            required=["ok", "enqueued", "request"],
        ),
        "ingestion_queue_list": object_schema(
            {
                "requests": {"type": "array"},
                "count": {"type": "integer"},
            },
            required=["requests", "count"],
        ),
        "ingestion_process": object_schema(
            {
                "ok": {"type": "boolean"},
                "apply": {"type": "boolean"},
                "processed": {"type": "integer"},
                "requests": {"type": "array"},
            },
            required=["ok", "apply", "processed", "requests"],
        ),
        "codex_hook_ingest": object_schema(
            {
                "ok": {"type": "boolean"},
                "hook_event_name": {"type": ["string", "null"]},
                "session_id": {"type": ["string", "null"]},
                "codex_home": {"type": ["string", "null"]},
                "enqueue": {"type": ["object", "null"]},
                "process": {"type": ["object", "null"]},
                "hook_response": {"type": "object"},
                "error": {"type": "string"},
            },
            required=["ok", "hook_event_name", "codex_home", "enqueue", "process", "hook_response"],
        ),
        "codex_hook_config": object_schema(
            {
                "hooks": {"type": "object"},
            },
            required=["hooks"],
        ),
        "codex_hook_install": object_schema(
            {
                "ok": {"type": "boolean"},
                "apply": {"type": "boolean"},
                "path": {"type": "string"},
                "action": {"type": "string"},
                "config": {"type": "object"},
                "trust_required": {"type": "boolean"},
            },
            required=["ok", "apply", "path", "action", "config", "trust_required"],
        ),
        "codex_integration_status": object_schema(
            {
                "contract_version": {"type": "string"},
                "ok": {"type": "boolean"},
                "healthy": {"type": "boolean"},
                "codex_home": {"type": "string"},
                "db_path": {"type": "string"},
                "threadvault_executable": {"type": "string"},
                "hook": {"type": "object"},
                "mcp": {"type": "object"},
                "source_freshness": {"type": "object"},
                "recommended_actions": {"type": "array", "items": {"type": "string"}},
            },
            required=[
                "contract_version", "ok", "healthy", "codex_home", "db_path",
                "threadvault_executable", "hook", "mcp", "source_freshness", "recommended_actions",
            ],
        ),
        "codex_integration_install": object_schema(
            {
                "contract_version": {"type": "string"},
                "ok": {"type": "boolean"},
                "applied": {"type": "boolean"},
                "hook": {"type": "object"},
                "mcp": {"type": "object"},
                "status": {"type": "object"},
                "restart_required": {"type": "boolean"},
                "hook_trust_required": {"type": "boolean"},
            },
            required=[
                "contract_version", "ok", "applied", "hook", "mcp", "status",
                "restart_required", "hook_trust_required",
            ],
        ),
        "export_target_manifest": object_schema(
            {
                "manifest_version": {"type": "string"},
                "target_profile": {"type": "string"},
                "generated_at": {"type": "string"},
                "root": {"type": "string"},
                "selection": {"type": "object"},
                "files": {"type": "array"},
                "skipped": {"type": "array"},
                "privacy": {"type": "object"},
                "evidence": {"type": "object"},
            },
            required=[
                "manifest_version",
                "target_profile",
                "generated_at",
                "root",
                "selection",
                "files",
                "skipped",
                "privacy",
                "evidence",
            ],
        ),
        "retrieval_query": object_schema(
            {
                "contract_version": {"type": "string"},
                "query": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["text", "limit", "fields", "mode"],
                    "properties": {
                        "text": {"type": "string"},
                        "limit": {"type": "integer"},
                        "fields": {"type": "string", "enum": ["minimal", "standard", "full"]},
                        "mode": {"type": "string"},
                    },
                },
                "diagnostics": retrieval_diagnostics_properties(),
                "results": {
                    "type": "array",
                    "items": object_schema(search_standard_properties(include_rank=True), required=["event_id", "session_id"]),
                },
            },
            required=["contract_version", "query", "diagnostics", "results"],
        ),
        "retrieval_diagnostics": object_schema(
            {
                "contract_version": {"type": "string"},
                "diagnostics": retrieval_diagnostics_properties(),
            },
            required=["contract_version", "diagnostics"],
        ),
        "hybrid_retrieval": object_schema(
            {
                "contract_version": {"type": "string"},
                "query": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["text", "limit", "vector_limit", "filters"],
                    "properties": {
                        "text": {"type": "string"},
                        "limit": {"type": "integer"},
                        "vector_limit": {"type": "integer"},
                        "filters": {"type": "object"},
                    },
                },
                "results": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": True,
                        "required": [
                            "hybrid_id",
                            "source",
                            "score",
                            "scores",
                            "session_id",
                            "event_id",
                            "chunk_id",
                            "chunk_type",
                            "text",
                            "evidence_event_ids",
                            "metadata",
                            "explanation",
                        ],
                        "properties": {
                            "hybrid_id": {"type": "string"},
                            "source": {"type": "string", "enum": ["fts", "vector"]},
                            "score": {"type": "number"},
                            "scores": {
                                "type": "object",
                                "additionalProperties": True,
                                "required": ["fts", "vector", "same_project", "exact_hint"],
                                "properties": {
                                    "fts": {"type": "number"},
                                    "vector": {"type": "number"},
                                    "same_project": {"type": "number"},
                                    "exact_hint": {"type": "number"},
                                },
                            },
                            "session_id": {"type": "string"},
                            "event_id": {"type": ["integer", "null"]},
                            "chunk_id": {"type": ["string", "null"]},
                            "chunk_type": {"type": ["string", "null"]},
                            "text": {"type": "string"},
                            "evidence_event_ids": {"type": "array", "items": {"type": "integer"}, "minItems": 1},
                            "metadata": {"type": "object"},
                            "explanation": {
                                "type": "object",
                                "additionalProperties": True,
                                "required": ["source", "matched_by", "rank_factors"],
                                "properties": {
                                    "source": {"type": "string"},
                                    "matched_by": {"type": "array", "items": {"type": "string"}},
                                    "rank_factors": {"type": "array"},
                                },
                            },
                        },
                    },
                },
                "diagnostics": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["capabilities_used", "fts", "vector", "ranking"],
                    "properties": {
                        "capabilities_used": {"type": "array", "items": {"type": "string"}},
                        "fts": {"type": "object"},
                        "vector": {"type": "object"},
                        "ranking": {"type": "object"},
                    },
                },
            },
            required=["contract_version", "query", "results", "diagnostics"],
        ),
        "agent_interface_manifest": object_schema(
            {
                "contract_version": {"type": "string"},
                "interface": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["name", "version", "module", "default_mode", "modes"],
                    "properties": {
                        "name": {"type": "string"},
                        "version": {"type": "string"},
                        "module": {"type": "string"},
                        "default_mode": {"type": "string", "enum": ["hybrid", "fts"]},
                        "modes": {"type": "array", "items": {"type": "string"}},
                    },
                },
                "capabilities": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["retrieval", "hybrid_retrieval", "fts_fallback", "vector_optional", "local_debug_available"],
                    "properties": {
                        "retrieval": {"type": "boolean"},
                        "hybrid_retrieval": {"type": "boolean"},
                        "fts_fallback": {"type": "boolean"},
                        "vector_optional": {"type": "boolean"},
                        "local_vector_enabled": {"type": "boolean"},
                        "local_debug_available": {"type": "boolean"},
                        "mcp_runtime_included": {"type": "boolean"},
                    },
                },
                "schemas": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["manifest", "retrieval", "underlying"],
                    "properties": {
                        "manifest": {"type": "string"},
                        "retrieval": {"type": "string"},
                        "underlying": {"type": "array", "items": {"type": "string"}},
                    },
                },
                "recommended_commands": {"type": "array", "items": {"type": "string"}},
                "privacy": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": [
                        "local_first",
                        "raw_paths_in_default_output",
                        "raw_transcript_paths_exposed",
                        "local_debug_opt_in",
                        "external_model_calls",
                    ],
                    "properties": {
                        "local_first": {"type": "boolean"},
                        "raw_paths_in_default_output": {"type": "boolean"},
                        "raw_transcript_paths_exposed": {"type": "boolean"},
                        "local_debug_opt_in": {"type": "boolean"},
                        "external_model_calls": {"type": "boolean"},
                    },
                },
                "defaults": {"type": "object"},
            },
            required=["contract_version", "interface", "capabilities", "schemas", "recommended_commands", "privacy", "defaults"],
        ),
        "agent_retrieval": object_schema(
            {
                "contract_version": {"type": "string"},
                "request": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["text", "requested_mode", "used_mode", "limit", "vector_limit", "filters"],
                    "properties": {
                        "text": {"type": "string"},
                        "requested_mode": {"type": "string", "enum": ["hybrid", "fts"]},
                        "used_mode": {"type": "string", "enum": ["hybrid", "fts"]},
                        "limit": {"type": "integer"},
                        "vector_limit": {"type": "integer"},
                        "filters": {"type": "object"},
                    },
                },
                "results": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": True,
                        "required": [
                            "result_id",
                            "source",
                            "score",
                            "session_id",
                            "event_id",
                            "chunk_id",
                            "text",
                            "evidence_event_ids",
                            "explanation",
                        ],
                        "properties": {
                            "result_id": {"type": "string"},
                            "source": {"type": "string", "enum": ["fts", "vector"]},
                            "score": {"type": "number"},
                            "session_id": {"type": "string"},
                            "event_id": {"type": ["integer", "null"]},
                            "chunk_id": {"type": ["string", "null"]},
                            "text": {"type": "string"},
                            "evidence_event_ids": {"type": "array", "items": {"type": "integer"}, "minItems": 1},
                            "explanation": {"type": "object"},
                            "metadata": {"type": "object"},
                            "scores": {"type": "object"},
                        },
                    },
                },
                "diagnostics": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["used_mode", "underlying_contract", "capabilities_used", "result_count"],
                    "properties": {
                        "used_mode": {"type": "string", "enum": ["hybrid", "fts"]},
                        "underlying_contract": {"type": "string"},
                        "capabilities_used": {"type": "array", "items": {"type": "string"}},
                        "result_count": {"type": "integer"},
                    },
                },
                "privacy": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["raw_paths_included", "local_debug", "external_model_calls"],
                    "properties": {
                        "raw_paths_included": {"type": "boolean"},
                        "local_debug": {"type": "boolean"},
                        "external_model_calls": {"type": "boolean"},
                    },
                },
            },
            required=["contract_version", "request", "results", "diagnostics", "privacy"],
        ),
        "mcp_manifest": object_schema(
            {
                "contract_version": {"type": "string"},
                "server": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["name", "module", "transport", "protocol_version", "version"],
                    "properties": {
                        "name": {"type": "string"},
                        "module": {"type": "string"},
                        "transport": {"type": "string", "enum": ["stdio"]},
                        "protocol_version": {"type": "string"},
                        "version": {"type": "string"},
                    },
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": True,
                        "required": ["name", "description", "input_schema"],
                        "properties": {
                            "name": {"type": "string"},
                            "description": {"type": "string"},
                            "input_schema": {"type": "object"},
                        },
                    },
                },
                "privacy": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": [
                        "local_first",
                        "cloud_sync",
                        "external_model_calls",
                        "raw_paths_in_default_output",
                        "local_debug_opt_in",
                        "writes_files",
                    ],
                    "properties": {
                        "local_first": {"type": "boolean"},
                        "cloud_sync": {"type": "boolean"},
                        "external_model_calls": {"type": "boolean"},
                        "raw_paths_in_default_output": {"type": "boolean"},
                        "local_debug_opt_in": {"type": "boolean"},
                        "writes_files": {"type": "boolean"},
                    },
                },
                "integration_guidance": {"type": "object"},
            },
            required=["contract_version", "server", "tools", "privacy", "integration_guidance"],
        ),
        "client_interface_manifest": object_schema(
            {
                "contract_version": {"type": "string"},
                "interface": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["name", "version", "module", "client_families"],
                    "properties": {
                        "name": {"type": "string"},
                        "version": {"type": "string"},
                        "module": {"type": "string"},
                        "client_families": {"type": "array", "items": {"type": "string"}},
                    },
                },
                "client_families": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": True,
                        "required": ["name", "status", "server_required", "recommended_entrypoints"],
                        "properties": {
                            "name": {"type": "string"},
                            "status": {"type": "string"},
                            "server_required": {"type": "boolean"},
                            "recommended_entrypoints": {"type": "array", "items": {"type": "string"}},
                        },
                    },
                },
                "entrypoints": {"type": "object"},
                "schemas": {"type": "object"},
                "defaults": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": [
                        "local_first",
                        "server_required",
                        "cloud_sync",
                        "external_model_calls",
                        "raw_paths_in_default_output",
                        "vector_enabled_by_default",
                        "local_vector_enabled",
                    ],
                    "properties": {
                        "local_first": {"type": "boolean"},
                        "server_required": {"type": "boolean"},
                        "cloud_sync": {"type": "boolean"},
                        "external_model_calls": {"type": "boolean"},
                        "raw_paths_in_default_output": {"type": "boolean"},
                        "vector_enabled_by_default": {"type": "boolean"},
                        "local_vector_enabled": {"type": "boolean"},
                    },
                },
                "integration_policy": {"type": "object"},
            },
            required=[
                "contract_version",
                "interface",
                "client_families",
                "entrypoints",
                "schemas",
                "defaults",
                "integration_policy",
            ],
        ),
        "client_overview": object_schema(
            {
                "contract_version": {"type": "string"},
                "request": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["query", "cwd", "limit", "local_debug"],
                    "properties": {
                        "query": {"type": ["string", "null"]},
                        "cwd": {"type": ["string", "null"]},
                        "limit": {"type": "integer"},
                        "local_debug": {"type": "boolean"},
                    },
                },
                "sessions": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": True,
                        "required": [
                            "session_id",
                            "cwd",
                            "source_kind",
                            "first_seen_at",
                            "updated_at",
                            "event_count",
                            "warning_count",
                        ],
                        "properties": {
                            "session_id": {"type": "string"},
                            "cwd": {"type": ["string", "null"]},
                            "source_kind": {"type": "string"},
                            "first_seen_at": {"type": ["string", "null"]},
                            "updated_at": {"type": ["string", "null"]},
                            "event_count": {"type": "integer"},
                            "warning_count": {"type": "integer"},
                            "raw_path": {"type": "string"},
                        },
                    },
                },
                "search": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["query", "results", "diagnostics"],
                    "properties": {
                        "query": {"type": ["string", "null"]},
                        "results": {"type": "array"},
                        "diagnostics": {"type": "object"},
                    },
                },
                "actions": {"type": "object"},
                "privacy": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["local_first", "raw_paths_included", "local_debug", "external_model_calls"],
                    "properties": {
                        "local_first": {"type": "boolean"},
                        "raw_paths_included": {"type": "boolean"},
                        "local_debug": {"type": "boolean"},
                        "external_model_calls": {"type": "boolean"},
                    },
                },
                "diagnostics": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["mode", "session_count", "search_result_count", "vector_enabled", "server_required"],
                    "properties": {
                        "mode": {"type": "string"},
                        "session_count": {"type": "integer"},
                        "search_result_count": {"type": "integer"},
                        "vector_enabled": {"type": "boolean"},
                        "server_required": {"type": "boolean"},
                    },
                },
            },
            required=["contract_version", "request", "sessions", "search", "actions", "privacy", "diagnostics"],
        ),
        "client_tui_runtime": object_schema(
            {
                "contract_version": {"type": "string"},
                "runtime": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["name", "family", "status", "module", "server_required", "cloud_sync"],
                    "properties": {
                        "name": {"type": "string"},
                        "family": {"type": "string"},
                        "status": {"type": "string"},
                        "module": {"type": "string"},
                        "server_required": {"type": "boolean"},
                        "cloud_sync": {"type": "boolean"},
                    },
                },
                "request": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": [
                        "query",
                        "cwd",
                        "limit",
                        "local_debug",
                        "export_preview_requested",
                        "export_preview_session",
                        "export_preview_profile",
                    ],
                    "properties": {
                        "query": {"type": ["string", "null"]},
                        "cwd": {"type": ["string", "null"]},
                        "limit": {"type": "integer"},
                        "local_debug": {"type": "boolean"},
                        "export_preview_requested": {"type": "boolean"},
                        "export_preview_session": {"type": ["string", "null"]},
                        "export_preview_profile": {"type": ["string", "null"]},
                    },
                },
                "screen": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["title", "sections", "session_rows", "search_rows", "export_rows"],
                    "properties": {
                        "title": {"type": "string"},
                        "sections": {"type": "array"},
                        "session_rows": {"type": "array"},
                        "search_rows": {"type": "array"},
                        "export_rows": {"type": "array"},
                    },
                },
                "overview": {"type": "object"},
                "export_preview": {"type": ["object", "null"]},
                "actions": {"type": "object"},
                "privacy": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": [
                        "local_first",
                        "raw_paths_included",
                        "raw_transcript_included",
                        "server_required",
                        "server_opt_in",
                        "cloud_sync",
                        "external_model_calls",
                        "export_preview_writes_files",
                    ],
                    "properties": {
                        "local_first": {"type": "boolean"},
                        "raw_paths_included": {"type": "boolean"},
                        "raw_transcript_included": {"type": "boolean"},
                        "server_required": {"type": "boolean"},
                        "server_opt_in": {"type": "boolean"},
                        "cloud_sync": {"type": "boolean"},
                        "external_model_calls": {"type": "boolean"},
                        "export_preview_writes_files": {"type": "boolean"},
                    },
                },
                "diagnostics": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": [
                        "mode",
                        "accepted_runtime",
                        "session_count",
                        "search_result_count",
                        "export_preview_included",
                        "export_preview_planned_file_count",
                        "overview_contract_version",
                        "export_preview_contract_version",
                        "server_required",
                        "v2_retrieval_reused",
                    ],
                    "properties": {
                        "mode": {"type": "string"},
                        "accepted_runtime": {"type": "boolean"},
                        "session_count": {"type": "integer"},
                        "search_result_count": {"type": "integer"},
                        "export_preview_included": {"type": "boolean"},
                        "export_preview_planned_file_count": {"type": "integer"},
                        "overview_contract_version": {"type": "string"},
                        "export_preview_contract_version": {"type": ["string", "null"]},
                        "server_required": {"type": "boolean"},
                        "v2_retrieval_reused": {"type": "boolean"},
                    },
                },
            },
            required=[
                "contract_version",
                "runtime",
                "request",
                "screen",
                "overview",
                "export_preview",
                "actions",
                "privacy",
                "diagnostics",
            ],
        ),
        "client_session": object_schema(
            {
                "contract_version": {"type": "string"},
                "request": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["session_id", "event_limit", "max_chars", "local_debug"],
                    "properties": {
                        "session_id": {"type": "string"},
                        "event_limit": {"type": "integer"},
                        "max_chars": {"type": "integer"},
                        "local_debug": {"type": "boolean"},
                    },
                },
                "session": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": [
                        "session_id",
                        "parent_session_id",
                        "cwd",
                        "source_kind",
                        "model_provider",
                        "first_seen_at",
                        "updated_at",
                        "archived",
                        "event_count",
                        "warning_count",
                    ],
                    "properties": {
                        "session_id": {"type": "string"},
                        "parent_session_id": {"type": ["string", "null"]},
                        "cwd": {"type": ["string", "null"]},
                        "source_kind": {"type": "string"},
                        "model_provider": {"type": ["string", "null"]},
                        "first_seen_at": {"type": ["string", "null"]},
                        "updated_at": {"type": ["string", "null"]},
                        "archived": {"type": "boolean"},
                        "event_count": {"type": "integer"},
                        "warning_count": {"type": "integer"},
                        "raw_path": {"type": "string"},
                    },
                },
                "summary": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["session_id", "topic", "evidence_event_ids", "evidence_coverage"],
                    "properties": {
                        "session_id": {"type": "string"},
                        "topic": {"type": "string"},
                        "user_goal": {"type": ["string", "null"]},
                        "key_steps": {"type": "array"},
                        "key_commands": {"type": "array"},
                        "files": {"type": "array"},
                        "problems": {"type": "array"},
                        "next_steps": {"type": "array"},
                        "evidence_event_ids": {"type": "array", "items": {"type": "integer"}},
                        "evidence_coverage": {"type": "object"},
                        "missing_evidence_warnings": {"type": "array", "items": {"type": "string"}},
                    },
                },
                "events": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": True,
                        "required": [
                            "event_id",
                            "turn_id",
                            "turn_index",
                            "timestamp",
                            "top_type",
                            "sub_type",
                            "role",
                            "tool_name",
                            "text_preview",
                            "truncated",
                        ],
                        "properties": {
                            "event_id": {"type": "integer"},
                            "turn_id": {"type": ["string", "null"]},
                            "turn_index": {"type": ["integer", "null"]},
                            "timestamp": {"type": ["string", "null"]},
                            "top_type": {"type": "string"},
                            "sub_type": {"type": ["string", "null"]},
                            "role": {"type": ["string", "null"]},
                            "tool_name": {"type": ["string", "null"]},
                            "text_preview": {"type": "string"},
                            "truncated": {"type": "boolean"},
                            "file_path": {"type": ["string", "null"]},
                            "line_no": {"type": ["integer", "null"]},
                        },
                    },
                },
                "actions": {"type": "object"},
                "privacy": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": [
                        "local_first",
                        "raw_paths_included",
                        "event_file_paths_included",
                        "raw_transcript_included",
                        "external_model_calls",
                    ],
                    "properties": {
                        "local_first": {"type": "boolean"},
                        "raw_paths_included": {"type": "boolean"},
                        "event_file_paths_included": {"type": "boolean"},
                        "raw_transcript_included": {"type": "boolean"},
                        "external_model_calls": {"type": "boolean"},
                    },
                },
                "diagnostics": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": [
                        "mode",
                        "event_count",
                        "events_returned",
                        "events_truncated",
                        "summary_evidence_count",
                        "server_required",
                    ],
                    "properties": {
                        "mode": {"type": "string"},
                        "event_count": {"type": "integer"},
                        "events_returned": {"type": "integer"},
                        "events_truncated": {"type": "integer"},
                        "summary_evidence_count": {"type": "integer"},
                        "server_required": {"type": "boolean"},
                    },
                },
            },
            required=["contract_version", "request", "session", "summary", "events", "actions", "privacy", "diagnostics"],
        ),
        "client_export_preview": object_schema(
            {
                "contract_version": {"type": "string"},
                "request": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["profile", "root", "sessions", "project", "privacy_mode"],
                    "properties": {
                        "profile": {"type": "string"},
                        "root": {"type": "string"},
                        "sessions": {"type": "array", "items": {"type": "string"}},
                        "project": {"type": ["string", "null"]},
                        "privacy_mode": {"type": "string"},
                    },
                },
                "selection": {"type": "object"},
                "planned_files": {"type": "array"},
                "skipped": {"type": "array"},
                "privacy": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["mode", "findings_count", "effective_findings_count", "blocked"],
                    "properties": {
                        "mode": {"type": "string"},
                        "findings_count": {"type": "integer"},
                        "effective_findings_count": {"type": "integer"},
                        "blocked": {"type": "boolean"},
                    },
                },
                "evidence": {"type": "object"},
                "actions": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["execute", "manifest_name"],
                    "properties": {
                        "execute": {"type": "string"},
                        "manifest_name": {"type": "string"},
                    },
                },
                "diagnostics": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": [
                        "preview",
                        "writes_files",
                        "manifest_written",
                        "planned_file_count",
                        "skipped_count",
                        "server_required",
                        "external_model_calls",
                    ],
                    "properties": {
                        "preview": {"type": "boolean"},
                        "writes_files": {"type": "boolean"},
                        "manifest_written": {"type": "boolean"},
                        "planned_file_count": {"type": "integer"},
                        "skipped_count": {"type": "integer"},
                        "server_required": {"type": "boolean"},
                        "external_model_calls": {"type": "boolean"},
                    },
                },
            },
            required=[
                "contract_version",
                "request",
                "selection",
                "planned_files",
                "skipped",
                "privacy",
                "evidence",
                "actions",
                "diagnostics",
            ],
        ),
        "client_warnings": object_schema(
            {
                "contract_version": {"type": "string"},
                "request": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["session_id", "local_debug"],
                    "properties": {
                        "session_id": {"type": "string"},
                        "local_debug": {"type": "boolean"},
                    },
                },
                "session": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["session_id", "cwd", "source_kind", "first_seen_at", "updated_at", "warning_count"],
                    "properties": {
                        "session_id": {"type": "string"},
                        "cwd": {"type": ["string", "null"]},
                        "source_kind": {"type": "string"},
                        "first_seen_at": {"type": ["string", "null"]},
                        "updated_at": {"type": ["string", "null"]},
                        "warning_count": {"type": "integer"},
                        "raw_path": {"type": "string"},
                    },
                },
                "warnings": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["items", "summary", "count"],
                    "properties": {
                        "items": {"type": "array"},
                        "summary": {"type": "object"},
                        "count": {"type": "integer"},
                    },
                },
                "privacy": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": [
                        "rules_version",
                        "findings",
                        "summary",
                        "has_effective_findings",
                        "raw_paths_included",
                        "raw_transcript_included",
                        "external_model_calls",
                    ],
                    "properties": {
                        "rules_version": {"type": "string"},
                        "config_path": {"type": ["string", "null"]},
                        "findings": {"type": "array"},
                        "summary": {"type": "object"},
                        "has_effective_findings": {"type": "boolean"},
                        "raw_paths_included": {"type": "boolean"},
                        "raw_transcript_included": {"type": "boolean"},
                        "external_model_calls": {"type": "boolean"},
                    },
                },
                "actions": {"type": "object"},
                "diagnostics": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": [
                        "mode",
                        "warning_count",
                        "privacy_finding_count",
                        "effective_privacy_finding_count",
                        "server_required",
                        "local_debug",
                    ],
                    "properties": {
                        "mode": {"type": "string"},
                        "warning_count": {"type": "integer"},
                        "privacy_finding_count": {"type": "integer"},
                        "effective_privacy_finding_count": {"type": "integer"},
                        "server_required": {"type": "boolean"},
                        "local_debug": {"type": "boolean"},
                    },
                },
            },
            required=["contract_version", "request", "session", "warnings", "privacy", "actions", "diagnostics"],
        ),
        "summary_chunks": object_schema(
            {
                "contract_version": {"type": "string"},
                "selection": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["sessions", "project", "selected_session_ids"],
                    "properties": {
                        "sessions": {"type": "array", "items": {"type": "string"}},
                        "project": {"type": ["string", "null"]},
                        "selected_session_ids": {"type": "array", "items": {"type": "string"}},
                    },
                },
                "chunks": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": True,
                        "required": [
                            "chunk_id",
                            "chunk_type",
                            "session_id",
                            "turn_index",
                            "text",
                            "text_chars",
                            "evidence_event_ids",
                            "metadata",
                        ],
                        "properties": {
                            "chunk_id": {"type": "string"},
                            "chunk_type": {"type": "string", "enum": ["session_summary", "turn_summary", "evidence"]},
                            "session_id": {"type": "string"},
                            "turn_index": {"type": ["integer", "null"]},
                            "text": {"type": "string"},
                            "text_chars": {"type": "integer"},
                            "evidence_event_ids": {"type": "array", "items": {"type": "integer"}, "minItems": 1},
                            "metadata": {"type": "object"},
                        },
                    },
                },
                "skipped": {"type": "array"},
                "diagnostics": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": [
                        "selected_sessions_count",
                        "chunks_count",
                        "chunk_type_counts",
                        "max_chunks_per_session",
                        "max_chars",
                        "truncated_chunks",
                        "embedding_ready",
                        "embedding_generated",
                    ],
                    "properties": {
                        "selected_sessions_count": {"type": "integer"},
                        "chunks_count": {"type": "integer"},
                        "chunk_type_counts": {"type": "object"},
                        "max_chunks_per_session": {"type": "integer"},
                        "max_chars": {"type": "integer"},
                        "truncated_chunks": {"type": "integer"},
                        "embedding_ready": {"type": "boolean"},
                        "embedding_generated": {"type": "boolean"},
                    },
                },
            },
            required=["contract_version", "selection", "chunks", "skipped", "diagnostics"],
        ),
        "vector_index": object_schema(
            {
                "contract_version": {"type": "string"},
                "ok": {"type": "boolean"},
                "adapter": {"type": "string"},
                "dimensions": {"type": "integer"},
                "source": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["schema", "selection", "skipped"],
                    "properties": {
                        "schema": {"type": "string"},
                        "selection": {"type": "object"},
                        "skipped": {"type": "array"},
                    },
                },
                "indexed": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["chunks", "total_chunks", "built_at"],
                    "properties": {
                        "chunks": {"type": "integer"},
                        "total_chunks": {"type": "integer"},
                        "built_at": {"type": "string"},
                    },
                },
                "diagnostics": vector_diagnostics_properties(),
            },
            required=["contract_version", "ok", "adapter", "dimensions", "source", "indexed", "diagnostics"],
        ),
        "vector_query": object_schema(
            {
                "contract_version": {"type": "string"},
                "query": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["text", "limit", "adapter", "dimensions"],
                    "properties": {
                        "text": {"type": "string"},
                        "limit": {"type": "integer"},
                        "adapter": {"type": "string"},
                        "dimensions": {"type": "integer"},
                    },
                },
                "results": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": True,
                        "required": [
                            "chunk_id",
                            "chunk_type",
                            "session_id",
                            "turn_index",
                            "score",
                            "text",
                            "evidence_event_ids",
                            "metadata",
                            "indexed_at",
                        ],
                        "properties": {
                            "chunk_id": {"type": "string"},
                            "chunk_type": {"type": "string"},
                            "session_id": {"type": "string"},
                            "turn_index": {"type": ["integer", "null"]},
                            "score": {"type": "number"},
                            "text": {"type": "string"},
                            "evidence_event_ids": {"type": "array", "items": {"type": "integer"}, "minItems": 1},
                            "metadata": {"type": "object"},
                            "indexed_at": {"type": "string"},
                        },
                    },
                },
                "diagnostics": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["config_enabled", "adapter", "dimensions", "indexed_chunks", "result_count"],
                    "properties": {
                        "config_enabled": {"type": "boolean"},
                        "adapter": {"type": "string"},
                        "dimensions": {"type": "integer"},
                        "indexed_chunks": {"type": "integer"},
                        "result_count": {"type": "integer"},
                        "embedding_kind": {"type": "string"},
                        "external_provider": {"type": "boolean"},
                    },
                },
            },
            required=["contract_version", "query", "results", "diagnostics"],
        ),
        "vector_status": object_schema(
            {
                "contract_version": {"type": "string"},
                "ok": {"type": "boolean"},
                "config": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["enabled", "adapter", "dimensions"],
                    "properties": {
                        "enabled": {"type": "boolean"},
                        "adapter": {"type": "string"},
                        "dimensions": {"type": "integer"},
                    },
                },
                "index": {
                    "type": "object",
                    "additionalProperties": True,
                    "required": ["exists", "adapter", "dimensions", "chunk_count", "built_at", "matching_chunks"],
                    "properties": {
                        "exists": {"type": "boolean"},
                        "adapter": {"type": ["string", "null"]},
                        "dimensions": {"type": ["integer", "null"]},
                        "chunk_count": {"type": "integer"},
                        "built_at": {"type": ["string", "null"]},
                        "matching_chunks": {"type": "integer"},
                    },
                },
                "diagnostics": vector_diagnostics_properties(),
            },
            required=["contract_version", "ok", "config", "index", "diagnostics"],
        ),
        "config_show": object_schema(
            {
                "requested_path": {"type": ["string", "null"]},
                "default_path": {"type": "string"},
                "resolved_path": {"type": "string"},
                "exists": {"type": "boolean"},
                "loaded": {"type": "boolean"},
                "loaded_path": {"type": ["string", "null"]},
                "sections": {"type": "array", "items": {"type": "string"}},
                "storage": {"type": "object"},
                "privacy": {"type": "object"},
                "audit_history": {"type": "object"},
                "backup_history": {"type": "object"},
                "restore_history": {"type": "object"},
            },
            required=[
                "requested_path",
                "default_path",
                "resolved_path",
                "exists",
                "loaded",
                "sections",
                "storage",
                "privacy",
                "audit_history",
                "backup_history",
                "restore_history",
            ],
        ),
        "config_doctor": object_schema(
            {
                "requested_path": {"type": ["string", "null"]},
                "default_path": {"type": "string"},
                "resolved_path": {"type": "string"},
                "exists": {"type": "boolean"},
                "ok": {"type": "boolean"},
                "errors": {"type": "array"},
                "warnings": {"type": "array"},
                "suggestions": {"type": "array", "items": {"type": "string"}},
                "summary": {"type": ["object", "null"]},
            },
            required=["requested_path", "default_path", "resolved_path", "exists", "ok", "errors", "warnings", "suggestions", "summary"],
        ),
        "config_init": object_schema(
            {
                "requested_path": {"type": ["string", "null"]},
                "default_path": {"type": "string"},
                "resolved_path": {"type": "string"},
                "exists": {"type": "boolean"},
                "ok": {"type": "boolean"},
                "created": {"type": "boolean"},
                "overwritten": {"type": "boolean"},
                "existed": {"type": "boolean"},
                "force": {"type": "boolean"},
                "error": {"type": ["string", "null"]},
                "doctor": {"type": "object"},
            },
            required=[
                "requested_path",
                "default_path",
                "resolved_path",
                "exists",
                "ok",
                "created",
                "overwritten",
                "existed",
                "force",
                "error",
                "doctor",
            ],
        ),
        "backup": object_schema(
            {
                "ok": {"type": "boolean"},
                "error": {"type": ["string", "null"]},
                "source_db": {"type": "string"},
                "destination": {"type": "string"},
                "existed": {"type": "boolean"},
                "overwritten": {"type": "boolean"},
                "force": {"type": "boolean"},
                "bytes": {"type": "integer"},
                "schema_version": {"type": ["integer", "null"]},
                "stats": {"type": ["object", "null"]},
                "manifest": {"type": ["object", "null"]},
            },
            required=[
                "ok",
                "error",
                "source_db",
                "destination",
                "existed",
                "overwritten",
                "force",
                "bytes",
                "schema_version",
                "stats",
                "manifest",
            ],
        ),
        "backup_verify": object_schema(
            {
                "backup": {"type": "string"},
                "exists": {"type": "boolean"},
                "ok": {"type": "boolean"},
                "errors": {"type": "array"},
                "integrity_check": {"type": ["array", "null"]},
                "schema_version": {"type": ["integer", "null"]},
                "doctor": {"type": ["object", "null"]},
                "stats": {"type": ["object", "null"]},
                "bytes": {"type": "integer"},
                "manifest": {"type": ["object", "null"]},
            },
            required=["backup", "exists", "ok", "errors", "integrity_check", "schema_version", "doctor", "stats", "bytes", "manifest"],
        ),
        "backup_manifest": object_schema(
            {
                "backup": {"type": "string"},
                "manifest": {"type": "string"},
                "exists": {"type": "boolean"},
                "ok": {"type": "boolean"},
                "errors": {"type": "array"},
                "manifest_data": {"type": ["object", "null"]},
            },
            required=["backup", "manifest", "exists", "ok", "errors", "manifest_data"],
        ),
        "restore_plan": object_schema(
            {
                "ok": {"type": "boolean"},
                "mode": {"type": "string"},
                "backup": {"type": "string"},
                "target_db": {"type": "string"},
                "backup_verification": {"type": "object"},
                "manifest_verification": {"type": "object"},
                "target": {"type": "object"},
                "errors": {"type": "array"},
                "warnings": {"type": "array"},
                "recommended_actions": {"type": "array", "items": {"type": "string"}},
            },
            required=[
                "ok",
                "mode",
                "backup",
                "target_db",
                "backup_verification",
                "manifest_verification",
                "target",
                "errors",
                "warnings",
                "recommended_actions",
            ],
        ),
        "restore": object_schema(
            {
                "ok": {"type": "boolean"},
                "mode": {"type": "string"},
                "apply": {"type": "boolean"},
                "overwrite": {"type": "boolean"},
                "allow_missing_manifest": {"type": "boolean"},
                "backup": {"type": "string"},
                "target_db": {"type": "string"},
                "plan": {"type": "object"},
                "pre_restore_backup": {"type": ["object", "null"]},
                "restored_verification": {"type": ["object", "null"]},
                "restored_doctor": {"type": ["object", "null"]},
                "history": {"type": ["object", "null"]},
                "errors": {"type": "array"},
                "warnings": {"type": "array"},
            },
            required=[
                "ok",
                "mode",
                "apply",
                "overwrite",
                "allow_missing_manifest",
                "backup",
                "target_db",
                "plan",
                "pre_restore_backup",
                "restored_verification",
                "restored_doctor",
                "history",
                "errors",
                "warnings",
            ],
        ),
        "restore_history_list": object_schema(
            {
                "history": {"type": "string"},
                "records": {"type": "array"},
                "warnings": {"type": "array"},
                "invalid_lines": {"type": "array", "items": {"type": "string"}},
            },
            required=["history", "records", "warnings", "invalid_lines"],
        ),
        "restore_history_latest": object_schema(
            {
                "history": {"type": "string"},
                "records": {"type": "array"},
                "warnings": {"type": "array"},
                "invalid_lines": {"type": "array", "items": {"type": "string"}},
                "latest": {"type": ["object", "null"]},
            },
            required=["history", "records", "warnings", "invalid_lines", "latest"],
        ),
        "restore_history_prune": object_schema(
            {
                "history": {"type": "string"},
                "records": {"type": "array"},
                "warnings": {"type": "array"},
                "invalid_lines": {"type": "array", "items": {"type": "string"}},
                "ok": {"type": "boolean"},
                "apply": {"type": "boolean"},
                "keep": {"type": "integer"},
                "keep_source": KEEP_SOURCE_SCHEMA,
                "kept": {"type": "array"},
                "deletable": {"type": "array"},
                "rewritten": {"type": "boolean"},
            },
            required=[
                "history",
                "records",
                "warnings",
                "invalid_lines",
                "ok",
                "apply",
                "keep",
                "keep_source",
                "kept",
                "deletable",
                "rewritten",
            ],
        ),
        "backup_history_list": object_schema(
            {
                "dir": {"type": "string"},
                "backups": {"type": "array"},
                "warnings": {"type": "array"},
            },
            required=["dir", "backups", "warnings"],
        ),
        "backup_history_latest": object_schema(
            {
                "dir": {"type": "string"},
                "backups": {"type": "array"},
                "warnings": {"type": "array"},
                "latest": {"type": ["object", "null"]},
            },
            required=["dir", "backups", "warnings", "latest"],
        ),
        "backup_history_verify_latest": object_schema(
            {
                "dir": {"type": "string"},
                "backups": {"type": "array"},
                "warnings": {"type": "array"},
                "latest": {"type": ["object", "null"]},
                "ok": {"type": "boolean"},
                "error": {"type": ["string", "null"]},
                "verification": {"type": ["object", "null"]},
            },
            required=["dir", "backups", "warnings", "latest", "ok", "error", "verification"],
        ),
        "backup_history_prune": object_schema(
            {
                "dir": {"type": "string"},
                "backups": {"type": "array"},
                "warnings": {"type": "array"},
                "ok": {"type": "boolean"},
                "apply": {"type": "boolean"},
                "keep": {"type": "integer"},
                "keep_source": KEEP_SOURCE_SCHEMA,
                "kept": {"type": "array"},
                "deletable": {"type": "array"},
                "deleted": {"type": "array", "items": {"type": "string"}},
            },
            required=["dir", "backups", "warnings", "ok", "apply", "keep", "keep_source", "kept", "deletable", "deleted"],
        ),
    }


def retrieval_diagnostics_properties() -> dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": True,
        "required": [
            "requested_mode",
            "used_mode",
            "engine",
            "fields",
            "limit",
            "filters",
            "fallback",
            "rank_strategy",
            "result_count",
            "index_status",
            "warnings",
        ],
        "properties": {
            "requested_mode": {"type": "string"},
            "used_mode": {"type": "string"},
            "engine": {"type": "string"},
            "fields": {"type": "string"},
            "limit": {"type": "integer"},
            "filters": {"type": "object"},
            "fallback": {"type": "object"},
            "rank_strategy": {"type": "string"},
            "result_count": {"type": "integer"},
            "index_status": {
                "type": "object",
                "additionalProperties": True,
                "required": ["ok", "event_count", "fts_count", "message"],
                "properties": {
                    "ok": {"type": "boolean"},
                    "event_count": {"type": ["integer", "null"]},
                    "fts_count": {"type": ["integer", "null"]},
                    "message": {"type": "string"},
                },
            },
            "warnings": {"type": "array", "items": {"type": "string"}},
        },
    }


def vector_diagnostics_properties() -> dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": True,
        "properties": {
            "config_enabled": {"type": "boolean"},
            "embedding_generated": {"type": "boolean"},
            "embedding_kind": {"type": "string"},
            "external_provider": {"type": "boolean"},
            "raw_events_indexed": {"type": "boolean"},
            "source_schema": {"type": "string"},
        },
    }


def audit_log_properties() -> dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": True,
        "required": ["path", "exists", "local_only", "server_required", "cloud_sync"],
        "properties": {
            "path": {"type": "string"},
            "exists": {"type": "boolean"},
            "local_only": {"type": "boolean"},
            "server_required": {"type": "boolean"},
            "cloud_sync": {"type": "boolean"},
        },
    }


def audit_record_properties() -> dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": True,
        "required": [
            "record_version",
            "record_id",
            "timestamp",
            "operation",
            "actor",
            "status",
            "target",
            "metadata",
            "local_only",
        ],
        "properties": {
            "record_version": {"type": "string"},
            "record_id": {"type": "string"},
            "timestamp": {"type": "string"},
            "operation": {"type": "string"},
            "actor": {"type": "string"},
            "status": {"type": "string"},
            "target": {
                "type": "object",
                "additionalProperties": True,
                "required": ["type", "id"],
                "properties": {
                    "type": {"type": "string"},
                    "id": {"type": "string"},
                },
            },
            "metadata": {"type": "object"},
            "local_only": {"type": "boolean"},
        },
    }


def audit_diagnostics_properties() -> dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": True,
        "required": ["record_count", "warning_count", "append_only", "server_required", "external_model_calls"],
        "properties": {
            "record_count": {"type": "integer"},
            "warning_count": {"type": "integer"},
            "append_only": {"type": "boolean"},
            "server_required": {"type": "boolean"},
            "external_model_calls": {"type": "boolean"},
        },
    }


def schema_names() -> list[str]:
    return sorted(contract_schemas())


def get_schema(name: str) -> dict[str, Any]:
    schemas = contract_schemas()
    if name not in schemas:
        raise KeyError(name)
    return schemas[name]


def write_schema_files(out_dir: Path) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    paths: list[Path] = []
    for name, schema in contract_schemas().items():
        path = out_dir / f"{name}.schema.json"
        path.write_text(json.dumps(schema, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        paths.append(path)
    return paths


def validate_payload(name: str, payload: Any) -> dict[str, Any]:
    schema = get_schema(name)
    validator = Draft202012Validator(schema)
    errors = sorted(validator.iter_errors(payload), key=lambda error: list(error.absolute_path))
    return {
        "ok": not errors,
        "schema": name,
        "contract_version": CONTRACT_VERSION,
        "errors": [
            {
                "path": list(error.absolute_path),
                "message": error.message,
                "validator": error.validator,
            }
            for error in errors
        ],
    }
